/*
   swossym.h - SWOS symbols header file

   Automatically generated from swos.map - do not edit
*/

#pragma once

extern dword swosCodeBase;
extern byte prevVideoMode;
extern word EGA_graphics;
extern void (*FindFiles[])();
extern void (*GameLoop[])();
extern void (*Flip[])();
extern void (*SWOS_EndProgram[])();
extern void (*ShowMenu[])();
extern void (*CalcMenuEntryAddress[])();
extern word controlWord;
extern word joy1Status;
extern word joy2Status;
extern void (*Joy2SetStatus[])();
extern void (*Player1StatusProc[])();
extern void (*Player2StatusProc[])();
extern char smallCharsTable[];
extern char *lin_adr_384k;
extern void (*ShowErrorMenu[])();
extern void (*SetExitMenuFlag[])();
/*
    controls
*/
extern word numLoopsJoy1;
extern word numLoopsJoy2;
/*
    SWOS original options
*/
extern word gameLength;
extern word autoReplays;
extern word menuMusic;
extern word autoSaveHighlights;
extern word allPlayerTeamsEqual;
extern word pitchType;
extern word commentary;
extern word chairmanScenes;
extern word joyKbdWord;
extern short sineCosineTable[256];
extern char *vsPtr;
/*
    68k register set
*/
extern dword D0;
extern dword D1;
extern dword D2;
extern dword D3;
extern dword D4;
extern dword D5;
extern dword D6;
extern dword D7;
extern dword A0;
extern dword A1;
extern dword A2;
extern dword A3;
extern dword A4;
extern dword A5;
extern dword A6;
extern void (*SaveSprite[])();
extern SpriteGraphics *spritesIndex[];
extern TeamGeneralInfo *benchTeam;
extern void (*SetCurrentEntry[])();
extern void (*DrawMenu[])();
extern void (*LoadDIYFile[])();
extern void (*PrimitivePrintf[])();
extern word numSelectedTeams;
extern byte selectedTeamsBuffer[];
extern word gameType;
extern byte pitch_dat_buffer[];
extern word inSubstitutesMenu;
extern void (*MainKeysCheck[])();
extern word lastKey;
extern void (*VerifyJoypadControls[])();
extern volatile ushort currentTick;
extern byte seed;
extern byte seed2;
extern void (*Rand[])();
extern void (*ReadGamePort[])();
extern char bigCharsTable[];
extern void (*GetKey[])();
/*
    custom tactics
*/
extern Tactics USER_A[];
extern Tactics USER_B[];
extern Tactics USER_C[];
extern Tactics USER_D[];
extern Tactics USER_E[];
extern Tactics USER_F[];
extern void (*Joy1SetStatus[])();
extern word longFireFlag;
extern void (*main_loop[])();
extern void (*ReadTimerDelta[])();
extern word teamSwitchCounter;
extern void (*InitTeamsData[])();
extern word left_team_player_no;
extern word left_team_coach_no;
extern word right_team_player_no;
extern word right_team_coach_no;
extern TeamGeneralInfo leftTeamData[];
extern TeamGeneralInfo rightTeamData[];
extern void (*SetupPlayers[])();
extern word random_seed;
extern volatile word stoppageTimer;
extern void (*TimerProc[])();
extern void (*CalculateIfPlayerWinsBall[])();
extern void (*UpdateStatistics[])();
extern word paused;
extern word showStats;
extern word showingStats;
extern void (*ClearBackground[])();
extern void (*AllowStatistics[])();
extern void (*StatisticsOff[])();
extern void (*TeamsControlsCheck[])();
extern word gameState;
extern word gameStatePl;
extern word replayState;
extern word bench1Called;
extern word bench2Called;
extern word halfNumber;
extern word replaySelected;
extern word playGame;
extern void (*AIL_stop_play[])();
extern word teamPlayingUp;
extern word pl1LastFired;
extern word pl2LastFired;
extern word pl1ShortFireCounter;
extern word pl2ShortFireCounter;
extern word gameStoppedTimer;
extern word goalCounter;
extern word stateGoal;
extern word benchCounter;
extern word benchCounter2;
extern word longFireCounter;
extern word longFireTime;
extern Sprite ballSprite[];
extern word frameCount;
extern void (*DrawSprites[])();
extern word numSpritesToRender;
extern Sprite *allSpritesArray[];
extern Sprite *sortedSprites[];
extern void (*SWOS_DrawSprite16Pixels[])();
extern byte deltaColor;
extern void (*DarkenRectangle[])();
extern short cameraX;
extern short cameraY;
extern void (*ScrollToCurrent[])();
extern dword gameTime;
extern void (*CopySprite[])();
extern char *selTeamsPtr;
extern SWOS_ScorerInfo team1Scorers[8];
extern SWOS_ScorerInfo team2Scorers[8];
extern word cameraXFraction;
extern word cameraYFraction;
extern Sprite team1Scorer1Sprite[];
extern Sprite team2Scorer1Sprite[];
extern void (*ClearSprite[])();
extern TeamGame *leftTeamPtr;
extern TeamGame *rightTeamPtr;
extern char *alreadyScoredTable[3];
extern char *firstGoalScoredTable[3];
extern void (*SWOS_Text2Sprite[])();
extern word animPatternsState;
extern void (*DrawAnimatedPatterns[])();
extern TeamStatsData team1StatsData[];
extern void (*DrawStatistics[])();
extern byte *advert1Pointers[8];
extern byte *advert2Pointers[8];
extern byte *advert3Pointers[8];
extern word statsTimeout;
extern word eventTimer;
extern void (*DrawSpriteInColor[])();
extern void (*DrawBenchAndSubsMenu[])();
extern void (*DrawBenchPlayersAndCoach[])();
extern void (*SWOS_DrawSpriteInGame[])();
extern void (*DrawSubstitutesMenu[])();
extern void (*DrawFormationMenu[])();
extern void (*SubstitutePlayerIfFiring[])();
extern void (*EnqueueSubstituteSample[])();
extern short subsState;
extern TeamGame *currentSubsTeam;
extern short plToBeSubstitutedPos;
extern short plToEnterGameIndex;
extern word selectedFormationEntry;
extern word subsMenuX;
extern short plToBeSubstitutedOrd;
extern short selectedPlayerInSubs;
extern word formationMenuX;
extern void (*LoadTeamFile[])();
extern char teamFileBuffer[];
extern void (*InitLittlePlayerSprites[])();
extern char editTacticsMenu[];
extern short chosenTactics;
extern char *chooseTacticsTeamPtr;
extern void (*DrawSpriteCentered[])();
extern void (*DrawLittlePlayersAndBall[])();
extern word pl1Tactics;
extern word pl2Tactics;
extern Tactics *tacticsTable[];
extern void (*ShowFormationMenu[])();
extern void (*ChangeFormationIfFiring[])();
extern void (*CheckContinueAbortPrompt[])();
extern char saveFileTitle[];
extern char saveFileName[];
extern void (*SaveCareerSelected[])();
extern void (*StartContest[])();
extern void (*PrepareMenu[])();
extern byte SWOS_MainMenu[];
extern TeamFile *playMatchTeam1Ptr;
extern TeamFile *playMatchTeam2Ptr;
extern Tactics tact_4_4_2[];
extern Tactics editTacticsCurrentTactics[];
/*
    Watcom C library
*/
extern void (*swos_libc_stackavail_[])();
extern void (*swos_libc_strncpy_[])();
extern void (*swos_libc_strlen_[])();
extern void (*swos_libc_strcmp_[])();
extern void (*swos_libc_strncmp_[])();
extern void (*swos_libc_strnicmp_[])();
extern void (*swos_libc_int386x_[])();
extern void (*swos_libc_segread_[])();
extern void (*swos_libc_exit_[])();
extern void (*swos_libc_memset_[])();
extern void (*swos_libc_memmove_[])();
extern void (*swos_libc_time_[])();
extern void (*swos_libc_ctime_[])();


#pragma aux swosCodeBase "*";
#pragma aux prevVideoMode "*";
#pragma aux EGA_graphics "*";
#pragma aux FindFiles "*";
#pragma aux GameLoop "*";
#pragma aux Flip "*";
#pragma aux SWOS_EndProgram "*";
#pragma aux ShowMenu "*";
#pragma aux CalcMenuEntryAddress "*";
#pragma aux controlWord "*";
#pragma aux joy1Status "*";
#pragma aux joy2Status "*";
#pragma aux Joy2SetStatus "*";
#pragma aux Player1StatusProc "*";
#pragma aux Player2StatusProc "*";
#pragma aux smallCharsTable "*";
#pragma aux lin_adr_384k "*";
#pragma aux ShowErrorMenu "*";
#pragma aux SetExitMenuFlag "*";
#pragma aux numLoopsJoy1 "*";
#pragma aux numLoopsJoy2 "*";
#pragma aux gameLength "*";
#pragma aux autoReplays "*";
#pragma aux menuMusic "*";
#pragma aux autoSaveHighlights "*";
#pragma aux allPlayerTeamsEqual "*";
#pragma aux pitchType "*";
#pragma aux commentary "*";
#pragma aux chairmanScenes "*";
#pragma aux joyKbdWord "*";
#pragma aux sineCosineTable "*";
#pragma aux vsPtr "*";
#pragma aux D0 "*";
#pragma aux D1 "*";
#pragma aux D2 "*";
#pragma aux D3 "*";
#pragma aux D4 "*";
#pragma aux D5 "*";
#pragma aux D6 "*";
#pragma aux D7 "*";
#pragma aux A0 "*";
#pragma aux A1 "*";
#pragma aux A2 "*";
#pragma aux A3 "*";
#pragma aux A4 "*";
#pragma aux A5 "*";
#pragma aux A6 "*";
#pragma aux SaveSprite "*";
#pragma aux spritesIndex "*";
#pragma aux benchTeam "*";
#pragma aux SetCurrentEntry "*";
#pragma aux DrawMenu "*";
#pragma aux LoadDIYFile "*";
#pragma aux PrimitivePrintf "*";
#pragma aux numSelectedTeams "*";
#pragma aux selectedTeamsBuffer "*";
#pragma aux gameType "*";
#pragma aux pitch_dat_buffer "*";
#pragma aux inSubstitutesMenu "*";
#pragma aux MainKeysCheck "*";
#pragma aux lastKey "*";
#pragma aux VerifyJoypadControls "*";
#pragma aux currentTick "*";
#pragma aux seed "*";
#pragma aux seed2 "*";
#pragma aux Rand "*";
#pragma aux ReadGamePort "*";
#pragma aux bigCharsTable "*";
#pragma aux GetKey "*";
#pragma aux USER_A "*";
#pragma aux USER_B "*";
#pragma aux USER_C "*";
#pragma aux USER_D "*";
#pragma aux USER_E "*";
#pragma aux USER_F "*";
#pragma aux Joy1SetStatus "*";
#pragma aux longFireFlag "*";
#pragma aux main_loop "*";
#pragma aux ReadTimerDelta "*";
#pragma aux teamSwitchCounter "*";
#pragma aux InitTeamsData "*";
#pragma aux left_team_player_no "*";
#pragma aux left_team_coach_no "*";
#pragma aux right_team_player_no "*";
#pragma aux right_team_coach_no "*";
#pragma aux leftTeamData "*";
#pragma aux rightTeamData "*";
#pragma aux SetupPlayers "*";
#pragma aux random_seed "*";
#pragma aux stoppageTimer "*";
#pragma aux TimerProc "*";
#pragma aux CalculateIfPlayerWinsBall "*";
#pragma aux UpdateStatistics "*";
#pragma aux paused "*";
#pragma aux showStats "*";
#pragma aux showingStats "*";
#pragma aux ClearBackground "*";
#pragma aux AllowStatistics "*";
#pragma aux StatisticsOff "*";
#pragma aux TeamsControlsCheck "*";
#pragma aux gameState "*";
#pragma aux gameStatePl "*";
#pragma aux replayState "*";
#pragma aux bench1Called "*";
#pragma aux bench2Called "*";
#pragma aux halfNumber "*";
#pragma aux replaySelected "*";
#pragma aux playGame "*";
#pragma aux AIL_stop_play "*";
#pragma aux teamPlayingUp "*";
#pragma aux pl1LastFired "*";
#pragma aux pl2LastFired "*";
#pragma aux pl1ShortFireCounter "*";
#pragma aux pl2ShortFireCounter "*";
#pragma aux gameStoppedTimer "*";
#pragma aux goalCounter "*";
#pragma aux stateGoal "*";
#pragma aux benchCounter "*";
#pragma aux benchCounter2 "*";
#pragma aux longFireCounter "*";
#pragma aux longFireTime "*";
#pragma aux ballSprite "*";
#pragma aux frameCount "*";
#pragma aux DrawSprites "*";
#pragma aux numSpritesToRender "*";
#pragma aux allSpritesArray "*";
#pragma aux sortedSprites "*";
#pragma aux SWOS_DrawSprite16Pixels "*";
#pragma aux deltaColor "*";
#pragma aux DarkenRectangle "*";
#pragma aux cameraX "*";
#pragma aux cameraY "*";
#pragma aux ScrollToCurrent "*";
#pragma aux gameTime "*";
#pragma aux CopySprite "*";
#pragma aux selTeamsPtr "*";
#pragma aux team1Scorers "*";
#pragma aux team2Scorers "*";
#pragma aux cameraXFraction "*";
#pragma aux cameraYFraction "*";
#pragma aux team1Scorer1Sprite "*";
#pragma aux team2Scorer1Sprite "*";
#pragma aux ClearSprite "*";
#pragma aux leftTeamPtr "*";
#pragma aux rightTeamPtr "*";
#pragma aux alreadyScoredTable "*";
#pragma aux firstGoalScoredTable "*";
#pragma aux SWOS_Text2Sprite "*";
#pragma aux animPatternsState "*";
#pragma aux DrawAnimatedPatterns "*";
#pragma aux team1StatsData "*";
#pragma aux DrawStatistics "*";
#pragma aux advert1Pointers "*";
#pragma aux advert2Pointers "*";
#pragma aux advert3Pointers "*";
#pragma aux statsTimeout "*";
#pragma aux eventTimer "*";
#pragma aux DrawSpriteInColor "*";
#pragma aux DrawBenchAndSubsMenu "*";
#pragma aux DrawBenchPlayersAndCoach "*";
#pragma aux SWOS_DrawSpriteInGame "*";
#pragma aux DrawSubstitutesMenu "*";
#pragma aux DrawFormationMenu "*";
#pragma aux SubstitutePlayerIfFiring "*";
#pragma aux EnqueueSubstituteSample "*";
#pragma aux subsState "*";
#pragma aux currentSubsTeam "*";
#pragma aux plToBeSubstitutedPos "*";
#pragma aux plToEnterGameIndex "*";
#pragma aux selectedFormationEntry "*";
#pragma aux subsMenuX "*";
#pragma aux plToBeSubstitutedOrd "*";
#pragma aux selectedPlayerInSubs "*";
#pragma aux formationMenuX "*";
#pragma aux LoadTeamFile "*";
#pragma aux teamFileBuffer "*";
#pragma aux InitLittlePlayerSprites "*";
#pragma aux editTacticsMenu "*";
#pragma aux chosenTactics "*";
#pragma aux chooseTacticsTeamPtr "*";
#pragma aux DrawSpriteCentered "*";
#pragma aux DrawLittlePlayersAndBall "*";
#pragma aux pl1Tactics "*";
#pragma aux pl2Tactics "*";
#pragma aux tacticsTable "*";
#pragma aux ShowFormationMenu "*";
#pragma aux ChangeFormationIfFiring "*";
#pragma aux CheckContinueAbortPrompt "*";
#pragma aux saveFileTitle "*";
#pragma aux saveFileName "*";
#pragma aux SaveCareerSelected "*";
#pragma aux StartContest "*";
#pragma aux PrepareMenu "*";
#pragma aux SWOS_MainMenu "*";
#pragma aux playMatchTeam1Ptr "*";
#pragma aux playMatchTeam2Ptr "*";
#pragma aux tact_4_4_2 "*";
#pragma aux editTacticsCurrentTactics "*";
#pragma aux swos_libc_stackavail_ "*";
#pragma aux swos_libc_strncpy_ "*";
#pragma aux swos_libc_strlen_ "*";
#pragma aux swos_libc_strcmp_ "*";
#pragma aux swos_libc_strncmp_ "*";
#pragma aux swos_libc_strnicmp_ "*";
#pragma aux swos_libc_int386x_ "*";
#pragma aux swos_libc_segread_ "*";
#pragma aux swos_libc_exit_ "*";
#pragma aux swos_libc_memset_ "*";
#pragma aux swos_libc_memmove_ "*";
#pragma aux swos_libc_time_ "*";
#pragma aux swos_libc_ctime_ "*";
